apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
      - name: dev-container
        image: us-central1-docker.pkg.dev/qwiklabs-gcp-04-a7f6f02bd37b/my-repository/hello-cloudbuild-dev:v2.0
        ports:
        - containerPort: 8080
